require_relative 'lib/sql_object'
require_relative 'cat'
require_relative 'house'
require_relative 'human'
require 'byebug'
require_relative 'lib/query_clauses/all_clauses'
require_relative 'lib/errors'
require_relative 'lib/assoc_options'
